- block:
    - name: "Kerberos | Copy GPG public key"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.copy:
        src: "{{ file_name }}"
        dest: /tmp/

    - name: "Kerberos | Import and trust GPG public key"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.shell:
        cmd: |
          gpg --import "/tmp/{{ file_name }}"
          echo "$( \
            gpg --list-keys \
            | grep "{{ file_name }}" | tail -1 \
            | tr -d '[:space:]' \
          ):6:" | gpg --import-ownertrust
