---
# tasks file for ansible_galaxy_role_kerberos

- name: "Kerberos | Add host to /etc/hosts"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: "{{ item.value }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.label }}"
  loop: "{{ kerberos_hosts | flatten(1) }}"

- name: "Kerberos | Install required packages"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.apt:
    pkg:
      - debconf
      - debconf-utils
      - expect
    state: present
    update_cache: yes
  tags:
    - packages

- name: "Kerberos | Create a directory for log files"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.file:
    path: /var/log/kerberos
    state: directory
    mode: "755"

- name: "Kerberos | Copy logrotate config file"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.copy:
    src: logrotate-kerberos
    dest: /etc/logrotate.d/kerberos
    owner: root
    mode: "644"

- name: "Kerberos | Check whether Kerberos packages are installed"
  become: true
  ignore_errors: true
  ansible.builtin.command: dpkg -l | grep -E "krb5-(admin-server|kdc)"
  register: kerberos_installed

- block:
    - name: "Kerberos | Copy an expect script to install Kerberos packages"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.copy:
        src: install_kerberos_packages.exp
        dest: /tmp
        owner: root
        mode: "775"

    - name: "Kerberos | Execute an expect script to install Kerberos packages"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.shell:
        cmd: |
          export MY_KERBEROS_DEFAULT_REALM="{{ kdc_my_realm }}"
          export MY_KERBEROS_SERVERS="{{ kerberos_my_servers }}"
          export MY_KERBEROS_ADMIN_SERVER="{{ kerberos_my_admin_server }}"
          ./install_kerberos_packages.exp
          unset KDC_MY_REALM
          unset MY_KERBEROS_SERVERS
          unset MY_KERBEROS_ADMIN_SERVER
        chdir: /tmp

  when: kerberos_installed.rc != 0

- name: "Kerberos | Replace kdc.conf"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.template:
    src: kdc.conf.j2
    dest: /etc/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: "644"

- name: "Kerberos | Check the Kerberos database"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.stat:
    path: /var/lib/krb5kdc/principal
  register: kerberos_database_path

- block:
    - name: "Kerberos | Copy an expect script to create KDC database"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.copy:
        src: create_kdc_database.exp
        dest: /tmp
        owner: root
        mode: "775"

    - name: "Kerberos | Execute an expect script to create KDC database"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.shell:
        cmd: |
          export KDC_MY_REALM="{{ kdc_my_realm }}"
          export KDC_MASTER_PASSWORD="{{ kdc_master_password }}"
          ./create_kdc_database.exp
          unset KDC_MY_REALM
          unset KDC_MASTER_PASSWORD
        chdir: /tmp

  when: (not kerberos_database_path.stat.exists)

- name: "Kerberos | Add administrators to the ACL file"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.copy:
    src: kadm5.acl
    dest: /etc/krb5kdc
    mode: "644"

- name: "Kerberos | Copy an expect script to add administrators to the Kerberos database"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.copy:
    src: add_admin_to_kerberos_database.exp
    dest: /tmp
    owner: root
    mode: "775"

- name: "Kerberos | Execute an expect script to add administrators to the Kerberos database"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.shell:
    cmd: |
      export MY_KERBEROS_ADMIN_PRINCIPAL="{{ kerberos_my_admin_principal }}@{{ kdc_my_realm }}"
      export MY_KERBEROS_ADMIN_PASSWORD="{{ kerberos_my_admin_password }}"
      ./add_admin_to_kerberos_database.exp
      unset MY_KERBEROS_ADMIN_PRINCIPAL
      unset MY_KERBEROS_ADMIN_PASSWORD
    chdir: /tmp

- name: "Kerberos | Start the Kerberos daemons on the primary KDC"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name:
      - krb5-admin-server
      - krb5-kdc
