---
# tasks file for ansible_galaxy_role_kerberos

- name: "Kerberos | Install required packages"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    pkg:
      - gpg
      - build-essential
      - bison
      - libssl-dev
      - libkrb5-dev
    state: present
    update_cache: yes

- name: "Kerberos | Import and trust GPG public key(s)"
  ansible.builtin.include_tasks:
    file: ./roles/kerberos/tasks/gpg_import_trust.yml
  vars:
    file_name: "{{ item }}"
  with_items:
    - 0CBA08575F8372DF
    - A32F17FD0055C305
    - CFE28FC7253AAB87

- name: "Kerberos | Download source code"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.get_url:
    url: https://kerberos.org/dist/krb5/1.21/krb5-1.21.3.tar.gz
    dest: /usr/local/src

- name: "Kerberos | Download signature file"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.get_url:
    url: https://kerberos.org/dist/krb5/1.21/krb5-1.21.3.tar.gz.asc
    dest: /tmp

- name: "Kerberos | Verify source code by GPG"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.command: gpg --verify /tmp/krb5-1.21.3.tar.gz.asc /usr/local/src/krb5-1.21.3.tar.gz
  register: kerberos_gpg_verify

- name: "Kerberos | Succeeded to verify"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.debug:
    msg: "GPG検証が成功しました。"
  when: kerberos_gpg_verify.rc == 0

- name: "Kerberos | Failed to verify"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.debug:
    msg: "GPG検証が失敗しました。"
  when: kerberos_gpg_verify.rc != 0

- name: "Kerberos | Unpack source code"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  unarchive:
    remote_src: yes
    src: /usr/local/src/krb5-1.21.3.tar.gz
    dest: /usr/local/src

- name: "Kerberos | Build source code"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.shell:
    cmd: |
      ./configure
      make
      make install
      make clean
      make distclean
    chdir: /usr/local/src/krb5-1.21.3/src

- name: "Kerberos | Copy krb5.conf"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.copy:
    src: krb5.conf
    dest: /usr/local/etc
    mode: "775"

- name: "Kerberos | Copy kdc.conf"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.copy:
    src: kdc.conf
    dest: /usr/local/var/krb5kdc
    mode: "775"
