#!/usr/bin/expect -f
set timeout -1
set password $env(KDC_MASTER_PASSWORD)

spawn kdb5_util create -s

expect {
    "Enter KDC database master key:" {
        send "$password\r"
        exp_continue
    }
    "Re-enter KDC database master key to verify:" {
        send "$password\r"
    }
    timeout {
        puts "タイムアウトエラーが発生しました"
        exit 1
    }
    eof {
        puts "予期せぬ終了が発生しました"
        exit 1
    }
}